version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
      - "5000:5000" 
    environment:
      - NODE_ENV=production
      - PORT=5000
      - FRONTEND_PORT=3000
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - app_data:/app/backend/data
      - ./backend/firebase-service-account.json:/app/backend/firebase-service-account.json
      - ./backend/.env:/app/backend/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  app_data:
    driver: local