name: Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_IMAGE_NAME: your-app-name  # Сменете!
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and tag Docker images
        run: |
          docker compose -f docker-compose.yml build
          docker tag your-app-name $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME:latest

      - name: Run tests (ако имате)
        run: |
          docker compose -f docker-compose.yml run app npm test

      - name: Push to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          docker push $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME:latest

  deploy:
    needs: build-test-push
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server (SSH)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull $DOCKER_HUB_USERNAME/$DOCKER_IMAGE_NAME:latest
            docker compose down
            docker compose up -d
